Question #0
What is ptrace?


The ptrace system call provides a means by which one process (the “tracer”) may examine and change the tracee’s memory and registers


ptrace is primarily used to implement breakpoint debugging and system call tracing


A system call


ptrace can only be found in some of Unix and Unix-like operating systems


It is an abbreviation of “process trace”


The ptrace system call provides a means by which one process (the “tracer”) may observe and control the execution of another process (the “tracee”)

Question #1
What is a system call?


The programmatic way in which a computer program requests a service from the kernel of the operating system it is executed on


malloc is a system call


System calls are much faster than regular library functions


printf is a system call


System calls provide an essential interface between a process and the operating system.


System calls only exist on Linux and Unix


fork is a system call


execve is a system call


read is a system call


Since the system calls are part of the OS, the application programs need to context switch from user space to kernel space whenever a system call is invoked

Question #2
What is strace?


strace is a tool one can use to disassemble an executable file (elf format only)


strace is a tool one can use to trace all the function calls made by a running process


strace is a tool one can use to trace all the system calls made by a running process

Question #3
What system call can we use to trace a running process?


ktrace


strace


ptrace
